name: '[FULL] ubuntu-16.04.'

on: [push]

jobs:
  build:
    runs-on: ubuntu-16.04

    steps:
      - uses: actions/checkout@v1

      - name: Update apt repos
        run: sudo apt-get update
        
      - name: Install Bitcoin PPA 
        run: sudo add-apt-repository ppa:bitcoin/bitcoin && sudo apt-get update

      - name: Install base dependencies
        run: sudo apt-get install build-essential libtool autotools-dev automake pkg-config bsdmainutils libattr1-dev make automake cmake curl g++-multilib binutils-gold python3 libssl-dev libdb4.8-dev libdb4.8++-dev
      
      - name: Install base dependencies
        run: sudo apt-get update && sudo apt-get install libqrencode-dev libboost-dev libboost-all-dev
          
      - name: make
        run: cd src/ && make -j4 -f makefile.unix USE_UPNP=- 
     
      - name: make check
        run: make check -j4
