name: '[FULL] ubuntu-18.04.'

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
        
      - name: Update apt repos
        run: sudo apt-get update
        
      - name: Install Bitcoin PPA 
        run: sudo apt-key adv --recv-keys --keyserver keyserver.ubuntu.com DFA2F90D && sudo apt-get update
    
      - name: Install base dependencies
        run: sudo apt-get install libssl1.0-dev libevent-dev build-essential libtool autotools-dev automake pkg-config make automake cmake curl libdb4.8-dev libdb4.8++-dev libqrencode-dev libboost-dev libboost-all-dev 
          
      - name: make
        run: cd src/ && make -j4 -f makefile.unix USE_UPNP=- 
     
      - name: make check
        run: make check -j4

      - name: make distcheck
        run: make distcheck
