name: '[FULL] ubuntu-16.04.'

on: [push]

jobs:
  build:
    runs-on: ubuntu-16.04

    steps:
      - uses: actions/checkout@v1

      - name: Update apt repos
        run: sudo apt-get update
        
    
      - name: Install ppa:bitcoin/bitcoin
        run: sudo add-apt-repository ppa:bitcoin/bitcoin && sudo apt-get update

      - name: Install base dependencies
        run: sudo apt-get install --allow-downgrades openssl1.0=1.0.2n-1ubuntu5.1 build-essential autoconf libtool libprotobuf-dev protobuf-compiler libevent-dev libqt4-dev libcanberra-gtk-module autotools-dev automake make cmake curl libdb-dev libdb++-dev libqrencode-dev libboost-dev libboost-all-dev 
          
      - name: make
        run: cd src/ && make -j22 -f makefile.unix USE_UPNP=- 
